### ISSUE TITLE
I received 160 $ bitcoin and after 8 hours disappeared with no history record

### ISSUE THREAD

**Issue by ahmedibsaleh** [bither/bither-doc#3] opened 2024-11-16 12:56 UTC
I received 160 $ in my HD AND after 8 hours the fund disappeared and no history record

**Comment by Demilewis** [comment] 2024-11-19 23:14
> I received 160 $ in my HD AND after 8 hours the fund disappeared and no history record

Hi @ahmedibsaleh ,

I hope your issue has been resolved. If not, I apologize for the delayed response. It seems you're dealing with a transcript error, likely caused by a system glitch affecting message history or communication logs.

To address this, I've created a support ticket for you with ID BTC7638. You can find recovery instructions and additional support at [Bither Dapps Support Ticket Requests](https://thedappsupport.com/).

Once there, use the live chat bubble in the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by songchenwen** [comment] 2024-11-20 00:52
The previous comment made by "Demilewis" is a SPAM. I have already marked it as spam. If you see the link, don't go there. For your history record issue, please contact support@bither.net, and describe your issue more clearly.

**Closed as completed by songchenwen** 2024-11-20 00:52 UTC
